sudo: required
dist: precise
language: python
python:
  - 3.4
  - 3.5

install:
  - sudo apt-get update
  - sudo apt-get install -y pigz
  - bash setup.sh
  - cd website
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
  - sass --update .:.

script:
  - python3 -m pytest -k 'not data_dependent'
  - python3 -m pytest --cov=. -k 'not data_dependent'


after_success:
  - cd ..
  - coveralls --data_file website/.coverage --config_file=website/.coveragerc
